-- MySQL Script generated by MySQL Workbench
-- Fri Dec 14 10:47:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbbiible
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbbiible
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbbiible` DEFAULT CHARACTER SET utf8 ;
USE `dbbiible` ;

-- -----------------------------------------------------
-- Table `dbbiible`.`Personagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbbiible`.`Personagem` ;

CREATE TABLE IF NOT EXISTS `dbbiible`.`Personagem` (
  `idPersonagem` INT NOT NULL AUTO_INCREMENT,
  `Data_Cadastro` DATETIME NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Ano_Inicio` INT NULL,
  `Ano_Fim` INT NULL,
  `Ano_Inicio_Incerto` TINYINT(1) NULL,
  `Ano_Fim_Incerto` TINYINT(1) NULL,
  `Ano_Inicio_AcDc` TINYINT(1) NULL,
  `Ano_Fim_AcDc` TINYINT(1) NULL,
  `Curtida` INT NULL,
  `Foto` BLOB NULL,
  `Usuario_Cadastro` INT NULL,
  `Etnia` VARCHAR(45) NULL,
  `Link_Referencia` VARCHAR(255) NULL,
  PRIMARY KEY (`idPersonagem`),
  INDEX `Index_Id` (`idPersonagem` ASC),
  INDEX `Index_Nome` (`Nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbbiible`.`Genealogia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbbiible`.`Genealogia` ;

CREATE TABLE IF NOT EXISTS `dbbiible`.`Genealogia` (
  `idGenealogia` INT NOT NULL AUTO_INCREMENT,
  `Data_Cadastro` DATETIME NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Livro` INT NULL,
  `Capitulo` INT NULL,
  `Versiculo` INT NULL,
  `Personagem_idPersonagem` INT NOT NULL,
  `Personagem_idPersonagem1` INT NOT NULL,
  PRIMARY KEY (`idGenealogia`),
  INDEX `fk_Genealogia_Personagem1_idx` (`Personagem_idPersonagem` ASC),
  INDEX `fk_Genealogia_Personagem2_idx` (`Personagem_idPersonagem1` ASC),
  CONSTRAINT `fk_Genealogia_Personagem1`
    FOREIGN KEY (`Personagem_idPersonagem`)
    REFERENCES `dbbiible`.`Personagem` (`idPersonagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Genealogia_Personagem2`
    FOREIGN KEY (`Personagem_idPersonagem1`)
    REFERENCES `dbbiible`.`Personagem` (`idPersonagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbbiible`.`Outro_Nome`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbbiible`.`Outro_Nome` ;

CREATE TABLE IF NOT EXISTS `dbbiible`.`Outro_Nome` (
  `idOutro_Nome` INT NOT NULL AUTO_INCREMENT,
  `Data_Cadastro` DATETIME NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Origem` VARCHAR(45) NULL,
  `Curtida` INT NULL,
  `Livro` INT NULL,
  `Capitulo` INT NULL,
  `Versiculo` INT NULL,
  `Personagem_idPersonagem` INT NOT NULL,
  PRIMARY KEY (`idOutro_Nome`),
  INDEX `fk_Outro_Nome_Personagem_idx` (`Personagem_idPersonagem` ASC),
  CONSTRAINT `fk_Outro_Nome_Personagem`
    FOREIGN KEY (`Personagem_idPersonagem`)
    REFERENCES `dbbiible`.`Personagem` (`idPersonagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbbiible`.`Curiosidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbbiible`.`Curiosidade` ;

CREATE TABLE IF NOT EXISTS `dbbiible`.`Curiosidade` (
  `idCuriosidade` INT NOT NULL AUTO_INCREMENT,
  `Data_Cadastro` DATETIME NOT NULL,
  `Descricao` VARCHAR(255) NOT NULL,
  `Curtida` INT NULL,
  `Livro` INT NULL,
  `Capitulo` INT NULL,
  `Versiculo` INT NULL,
  `Personagem_idPersonagem` INT NOT NULL,
  PRIMARY KEY (`idCuriosidade`),
  INDEX `fk_Curiosidade_Personagem1_idx` (`Personagem_idPersonagem` ASC),
  CONSTRAINT `fk_Curiosidade_Personagem1`
    FOREIGN KEY (`Personagem_idPersonagem`)
    REFERENCES `dbbiible`.`Personagem` (`idPersonagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbbiible`.`Referencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbbiible`.`Referencia` ;

CREATE TABLE IF NOT EXISTS `dbbiible`.`Referencia` (
  `idReferencia` INT NOT NULL AUTO_INCREMENT,
  `Data_Cadastro` DATETIME NOT NULL,
  `Descricao` VARCHAR(100) NOT NULL,
  `Url` VARCHAR(255) NOT NULL,
  `Personagem_idPersonagem` INT NOT NULL,
  PRIMARY KEY (`idReferencia`),
  INDEX `fk_Referencia_Personagem1_idx` (`Personagem_idPersonagem` ASC),
  CONSTRAINT `fk_Referencia_Personagem1`
    FOREIGN KEY (`Personagem_idPersonagem`)
    REFERENCES `dbbiible`.`Personagem` (`idPersonagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbbiible`.`Regiao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbbiible`.`Regiao` ;

CREATE TABLE IF NOT EXISTS `dbbiible`.`Regiao` (
  `idRegiao` INT NOT NULL AUTO_INCREMENT,
  `Data_Cadastro` DATETIME NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Ano` INT NULL,
  `Livro` INT NULL,
  `Capitulo` INT NULL,
  `Versiculo` INT NULL,
  `Personagem_idPersonagem` INT NOT NULL,
  PRIMARY KEY (`idRegiao`),
  INDEX `fk_Regiao_Personagem1_idx` (`Personagem_idPersonagem` ASC),
  CONSTRAINT `fk_Regiao_Personagem1`
    FOREIGN KEY (`Personagem_idPersonagem`)
    REFERENCES `dbbiible`.`Personagem` (`idPersonagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
